---
title: "shiny_presentation"
author: "Shailesh Rao"
date: "04/11/2020"
output: html_document
---

## Coursera Reproducible Pitch

### See the Regression Models Course Project  

- URL: *https://github.com/shaileshrao1999/developingprods*
---

## Dataset in use

### Motor Trend Car Road Tests

> The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973-74 models).
### Source
> Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391-411.

```{r}
library(datasets)
head(mtcars, 3)
```
---

## dataset in use - Format

**A data frame with 32 observations on 11 variables.**

| Index | Field | Detail |
------- | ----- | ------ |
| [, 1] | mpg | Miles/(US) gallon |
| [, 2]  | cyl | Number of cylinders |
| [, 3]	| disp | Displacement (cu.in.) |
| [, 4]	| hp | Gross horsepower |
| [, 5]	| drat | Rear axle ratio |
| [, 6]	| wt | Weight (lb/1000) |
| [, 7]	| qsec | 1/4 mile time |
| [, 8]	| vs | V/S |
| [, 9]	| am | Transmission (0 = automatic, 1 = manual) |
| [,10]	| gear | Number of forward gears |
| [,11]	| carb | Number of carburetors |

---


## Analysis - Ui code

```r
  library(shiny)

shinyUI(
    navbarPage("developing data products peer graded",
               tabPanel("given model",
                        fluidPage(
                            titlePanel("shows the correlation between mpg and the variables"),
                            sidebarLayout(
                                sidebarPanel(
                                    selectInput("variable", "Variable:",
                                                c("Number of cylinders" = "cyl",
                                                  "Displacement (cu.in.)" = "disp",
                                                  "Gross horsepower" = "hp",
                                                  "Rear axle ratio" = "drat",
                                                  "Weight (lb/1000)" = "wt",
                                                  "1/4 mile time" = "qsec",
                                                  "V/S" = "vs",
                                                  "Transmission" = "am",
                                                  "Number of forward gears" = "gear",
                                                  "Number of carburetors" = "carb"
                                                )),
                                    
                                    checkboxInput("outliers", "Show BoxPlot's outliers", FALSE)
                                ),
                                
                                mainPanel(
                                    h3(textOutput("Words")),
                                    
                                    tabsetPanel(type = "tabs", 
                                                tabPanel("BoxPlot", plotOutput("mpgBoxPlot")),
                                                tabPanel("Regression model", 
                                                         plotOutput("mpgPlot"),
                                                         verbatimTextOutput("fit")
                                                )
                                    )
                                )
                            )
                        )
               ),
               tabPanel("summary of the dataset",
                        
                        h3("Peer graded data science specialization"),
                        helpText("we try to find out whether an automatic car or a manual car gives better mileage per gallon with respect to the variables in the dataset",
                                 "between a set of variables and miles per gallon (MPG) (outcome). They are particularly interested in the following two questions: Is an automatic or manual transmission better for MPG. Quantify the MPG difference between automatic and manual transmissions"),
                        h3("Important"),
                        p("A data frame with 32 observations on 11 variables."),
                        
                        a("https://class.coursera.org/regmods-008")
               ),
               tabPanel("lets dive in deeper",
                        h2("in field car testing"),
                        hr(),
                        h3("Description"),
                        helpText("The data was extracted from the 1974 Motor Trend US magazine,",
                                 " and comprises fuel consumption and 10 aspects of automobile design and performance",
                                 " for 32 automobiles (1973-74 models)."),
                        h3("Format"),
                        p("A data frame with 32 observations on 11 variables."),
                        
                        p("  [, 1]   mpg         Miles/(US) gallon"),
                        p("  [, 2]	 cyl	 Number of cylinders"),
                        p("  [, 3]	 disp	 Displacement (cu.in.)"),
                        p("  [, 4]	 hp	 Gross horsepower"),
                        p("  [, 5]	 drat	 Rear axle ratio"),
                        p("  [, 6]	 wt	 Weight (lb/1000)"),
                        p("  [, 7]	 qsec	 1/4 mile time"),
                        p("  [, 8]	 vs	 V/S"),
                        p("  [, 9]	 am	 Transmission (0 = automatic, 1 = manual)"),
                        p("  [,10]	 gear	 Number of forward gears"),
                        p("  [,11]	 carb	 Number of carburetors"),
                        
                        h3("Source"),
                        
                        p("Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391-411.")
               ),
               tabPanel("student credentials",
                        a("https://github.com/shaileshrao1999/developingprods"),
                        hr(),
                        h4("This is my first shiny app"),
                        h4("I saved this in my github: shaileshrao1999")
               )
    )
)
```

## Analysis - Server code

```r
  library(shiny)
library(datasets)

#Shiny is an R package that allows you to easily build interactive web applications.
#The benefit of using Shiny is that it makes it possible to extend your R code to the web that would essentially help to expand its usability to a wider community (i.e. from being used by a single user to being used by hundreds or thousands of users via the internet).

datasetinuse <- mtcars
datasetinuse$am <- factor(datasetinuse$am, labels = c("Automatic", "Manual"))

shinyServer(function(input, output) {
    
    givencontent <- reactive({
        paste("mpg ~", input$variable)
    })
    
    givencontentPoint <- reactive({
        paste("mpg ~", "as.integer(", input$variable, ")")
    })
    
    modelinuse <- reactive({
        lm(as.formula(givencontentPoint()), data=datasetinuse)
    })
    
    output$caption <- renderText({
        givencontent()
    })
    
    output$mpgBoxPlot <- renderPlot({
        boxplot(as.formula(givencontent()), 
                data = datasetinuse,
                outline = input$outliers)
    })
    
    output$modelinuse <- renderPrint({
        summary(modelinuse())
    })
    
    output$mpgPlot <- renderPlot({
        with(datasetinuse, {
            plot(as.formula(givencontentPoint()))
            abline(modelinuse(), col=2)
        })
    })
    
})


```